# Generated by Django 3.2.4 on 2021-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitor_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
