# Generated by Django 3.2.4 on 2021-07-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
